# Generated by Django 4.2.6 on 2023-11-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nuevo_escalador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nivel', models.CharField(max_length=256)),
                ('preferencia', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
