# Generated by Django 4.2.6 on 2023-11-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escaladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nueva_ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=256)),
                ('grado', models.CharField(max_length=256)),
                ('nombre_parque', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='nuevo_bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bloque', models.CharField(max_length=256)),
                ('grado', models.CharField(max_length=256)),
                ('nombre_parque', models.CharField(max_length=256)),
            ],
        ),
    ]
