# Generated by Django 4.2.6 on 2023-11-25 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escaladores', '0003_nueva_ruta_creador_nuevo_bloque_creador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('subtitulo', models.DateField(blank=True, null=True)),
                ('cuerpo', models.CharField(max_length=10000)),
                ('autor', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha', models.DateTimeField()),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
