# Generated by Django 4.2.6 on 2023-11-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escaladores', '0004_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
