# Generated by Django 4.2.6 on 2023-11-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escaladores', '0005_alter_blog_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cuerpo',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.CharField(max_length=20),
        ),
    ]
