# Generated by Django 4.2.6 on 2023-11-25 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escaladores', '0006_alter_blog_cuerpo_alter_blog_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='fecha',
        ),
    ]
