# Generated by Django 4.2.6 on 2023-11-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escaladores', '0007_remove_blog_creador_remove_blog_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
