# Generated by Django 4.2.6 on 2023-11-25 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escaladores', '0008_blog_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
