# Generated by Django 4.2.6 on 2023-11-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escaladores', '0010_alter_blog_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
