# Generated by Django 4.2.6 on 2023-11-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escaladores', '0013_rename_fecha_blog_fech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='fech',
        ),
    ]
